### ISSUE TITLE
Equivalent to old confirmPaymentIntent

### ISSUE THREAD

**Issue by voneddy** [capacitor-community/stripe#234]
Hi all,
Sorry to post but can't find a solution in your docs or code...

**Is your feature request related to a problem? Please describe.**
I'm in the process upgrading a large complex app to capasitor 4 from v2, there's one outstanding issue though. Is there an equivalent to your old confirmPaymentIntent method in your newer plugin version?

**Describe the solution you'd like**
We have payments on the server side, using setup intents, that are hitting further action required, aka, they need 3ds2 auth...

So we just need a client side method like the old confirmPaymentIntent, to auth, is this possible currently?

Thanks for your time, and awesome work on this plugin

**Comment by ottojaa** [comment]
We have the same issue, to me it seems that this plugin has the necessary functionalities to enable saving payment method information for future usage, but there is no way to use saved payment methods with it. Marketplace implementations in EU require SCA compliant payment flows, which means that saved payment method information needs to be confirmed on the client due to the possible SCA authentication requests that cannot be completed on the server.

Is it expected to use the stripe APIs directly to confirm payments with saved payment method information? Given that this plugin already uses `confirmCardPayment` internally, exposing it would probably not be difficult from technical perspective, but perhaps there is a reason for not including it.

**Comment by voneddy** [comment]
Hi all. 
@ottojaa pretty I think ``` confirmCardPayment ``` is web only.

I'm not an iOS dev but looks like [STPAPIClient](https://stripe.dev/stripe-ios/docs/Classes/STPAPIClient.html#/c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmPaymentIntentWithParams:completion:) could be used in iOS? Not sure on Droid yet to be honest  

It used to be in here, so like you say maybe it's by design its been taken out...

All the best,
John

**Comment by rdlabo** [comment]
I missed this Issue and am late in responding. Sorry!

Simply because Stripe has deprecated the confirmPaymentIntent to be executed client-side. Please do this process on the server side.

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. Please create a new Issue if necessary.

**Comment by voneddy** [comment]
Hi @rdlabo no worries. Just checking how we are supposed to handle setup intents, that are hitting further action required, aka, they need 3ds2 auth? As in further action required means the client needs to run the card through SCA pop ups via the bank right?
