### ISSUE TITLE
confirmPaymentIntent is deprecated

### ISSUE THREAD

**Issue by stefanotauriello** [capacitor-community/stripe#39]
Like Stripe says here (https://stripe.com/docs/js/deprecated/confirm_payment_intent) confirmPaymenIntent is deprecated, it should be used confirmCardPayment.
Is it possible or we can only use confirmPaymentIntent?

Thanks

**Comment by ihadeed** [comment]
I'll look into this when updating the plugin in the near future. 

Since they don't have plans to remove that function for now, we'll likely have both functions available until they remove `confirmPaymentIntent`.

It seems like they're splitting `confirmPaymentIntent` into multiple methods that are specific for the source that's being used:
![image](https://user-images.githubusercontent.com/13794420/101693699-fc966f00-3a3f-11eb-8255-8f3f3ce84eb7.png)

**Comment by stefanotauriello** [comment]
Yes i know, but in order to avoid problems, it’s very equal apart of parameters, so of you can it will be very appreciated 🙏

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
